server:
  port: 8081

spring:

  application:
    name: customer-service

  datasource:
    url: jdbc:mysql://localhost:3306/customer_db
    username: root
    password: 23092005

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true